import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { authenticatedApi } from '@/config/api';

// Register the plugin
(jsPDF as any).autoTable = autoTable;

export interface FuelCostCenterRow {
    no: number;
    costCenter: string;
    totalAmount: number;
}

export interface FuelCostCenterReportProps {
    date: string;
    refNo: string;
    rows: FuelCostCenterRow[];
    subTotal: number;
    rounding: number;
    discount: number;
    grandTotal: number;
}

export async function generateFuelCostCenterReport({ stmt_id }: { stmt_id: number }) {
    const res = await authenticatedApi.get(`/api/bills/fuel/${stmt_id}`);
    const data = (res.data as { data: any }).data;

    let allRows: any[] = [];

    if (data && Array.isArray(data.costcenter_summ)) {
        allRows = data.costcenter_summ.map((cc: any, index: number) => ({
            no: index + 1,
            costCenter: cc.name,
            totalAmount: parseFloat(cc.total_amount || '0'),
        }));
    }

    if (!allRows.length) {
        throw new Error('No cost center summary data found for this statement.');
    }

    // Extract fuel issuer information
    const issuer = data?.fuel_issuer?.issuer || 'Fuel Provider';

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Function to add header and footer to current page
    const addHeaderFooter = async (pageNumber: number, totalPages: number) => {
        // Add header logo if available
        const logoUrl = process.env.NEXT_PUBLIC_BRAND_LOGO_LIGHT;
        if (logoUrl) {
            try {
                const response = await fetch(logoUrl);
                const blob = await response.blob();
                const reader = new FileReader();
                const base64Promise = new Promise<string>((resolve, reject) => {
                    reader.onloadend = () => resolve(reader.result as string);
                    reader.onerror = reject;
                });
                reader.readAsDataURL(blob);
                const base64 = await base64Promise;
                doc.addImage(base64, 'PNG', pageWidth - 32, 14, 18, 28);
            } catch (e) {
                // If logo fails to load, continue without it
            }
        }

        // Add footer logo if available
        const footerLogoUrl = process.env.NEXT_PUBLIC_REPORT_FOOTER_LOGO;
        if (footerLogoUrl) {
            try {
                const response = await fetch(footerLogoUrl);
                const blob = await response.blob();
                const reader = new FileReader();
                const base64Promise = new Promise<string>((resolve, reject) => {
                    reader.onloadend = () => resolve(reader.result as string);
                    reader.onerror = reject;
                });
                reader.readAsDataURL(blob);
                const base64 = await base64Promise;
                const imgWidth = 215;
                const imgHeight = 26;
                const x = (pageWidth - imgWidth) / 2;
                const pageHeight = doc.internal.pageSize.getHeight();
                doc.addImage(base64, 'PNG', x, pageHeight - imgHeight - 5, imgWidth, imgHeight); // right (lower number close to the right), top (lower number close to the top), width, height
            } catch (e) {
                // If logo fails to load, continue without it
            }
        }

        // Add "Generated by ADMS4" text
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.text('This document is generated by ADMS4', pageWidth / 2, pageHeight - 35, { align: 'center' });
        
        // Add page number
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(8);
        doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth / 2, pageHeight - 5, { align: 'center' });
    };

    // Add header and footer to first page
    await addHeaderFooter(1, 1); // Will be updated later with correct total

    // Add logo if available
    const logoUrl = process.env.NEXT_PUBLIC_BRAND_LOGO_LIGHT;
    if (logoUrl) {
        try {
            // Fetch the image and convert to base64
            const response = await fetch(logoUrl);
            const blob = await response.blob();
            const reader = new FileReader();
            const base64Promise = new Promise<string>((resolve, reject) => {
                reader.onloadend = () => resolve(reader.result as string);
                reader.onerror = reject;
            });
            reader.readAsDataURL(blob);
            const base64 = await base64Promise;
            doc.addImage(base64, 'PNG', pageWidth - 32, 14, 18, 28); // right (lower number close to the right), top (lower number close to the top), width, height
        } catch (e) {
            // If logo fails to load, continue without it
        }
    }

    // Header - Fixed Content
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('M E M O', pageWidth / 15, 24, { align: 'left' }); // right (lower number close to the right), top (lower number close to the top)

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`Our Ref : ${stmt_id}`, 15, 34);
    doc.text(`Date : ${new Date().toLocaleDateString()}`, pageWidth - 70, 34, { align: 'right' });

    doc.text('To      : Head of Finance', 15, 44);
    doc.text('Of      : Ranhill Technologies Sdn Bhd', pageWidth - 95, 44, { align: 'left' });
    doc.text('Copy  :', 15, 48);
    doc.text('Of      :', pageWidth - 95, 48, { align: 'left' });
    doc.text('From  : Human Resource & Administration', 15, 52);
    doc.text('Of      : Ranhill Technologies Sdn Bhd', pageWidth - 95, 52, { align: 'left' });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);


    doc.text('FUEL BILLS - JUNE 2025', 15, 64);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(`Kindly please make a payment to ${issuer} as follows:`, 15, 70);

    // Table with columns: No, Cost Center, Total Amount
    let y = 75;
    const tableHeaderRow = [
        'No', 'Cost Center', 'Total Amount (RM)'
    ];

    // Combine both staff cost and other rows into one table body with sequential numbering
    const tableBody = allRows.map((row) => [
        String(row.no),
        row.costCenter,
        row.totalAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })
    ]);

    autoTable(doc, {
        startY: y,
        head: [tableHeaderRow],
        body: tableBody,
        styles: { font: 'helvetica', fontSize: 9, cellPadding: 1 },
        headStyles: {
            fontStyle: 'bold',
            fillColor: [255, 255, 255],
            textColor: [0, 0, 0]
        },
        didDrawCell: function (data) {
            if (data.section === 'head') {
                const { cell } = data;
                const doc = data.doc;
                doc.setDrawColor(200);
                doc.setLineWidth(0.1);
                doc.rect(cell.x, cell.y, cell.width, cell.height);
            }
        },
        columnStyles: {
            0: { cellWidth: 12, halign: 'center' },
            1: { cellWidth: 120, halign: 'left' },
            2: { cellWidth: 45, halign: 'right' },
        },
        margin: { left: 14, right: 14 },
        tableWidth: 'auto',
        theme: 'grid',
        didDrawPage: (data) => {
            if (data.cursor) {
                y = data.cursor.y;
            }
        },
    });

    // Get current Y position after table
    y = (doc as any).lastAutoTable.finalY;

    // Add totals below the table using autoTable for consistent formatting
    const subtotalValue = parseFloat(data.stmt_stotal || '0').toLocaleString(undefined, { minimumFractionDigits: 2 });
    const roundingValue = parseFloat(data.stmt_rounding || '0').toLocaleString(undefined, { minimumFractionDigits: 2 });
    const discountValue = parseFloat(data.stmt_disc || '0').toLocaleString(undefined, { minimumFractionDigits: 2 });
    const grandTotalValue = parseFloat(data.stmt_total || '0').toLocaleString(undefined, { minimumFractionDigits: 2 });

    const totalsData = [
        ['', 'Sub-Total (RM):', subtotalValue],
        ['', 'Rounding (RM):', roundingValue],
        ['', 'Discount/Rebate (RM):', discountValue],
        ['', 'Grand Total (RM):', grandTotalValue]
    ];

    autoTable(doc, {
        startY: y,
        body: totalsData,
        styles: {
            font: 'helvetica',
            fontSize: 9,
            cellPadding: 1,
            fontStyle: 'bold',
            fillColor: [255, 255, 255]
        },
        alternateRowStyles: {
            fillColor: [255, 255, 255]
        },
        columnStyles: {
            0: { cellWidth: 12, halign: 'center' },
            1: { cellWidth: 120, halign: 'right' },
            2: { cellWidth: 45, halign: 'right' },
        },
        margin: { left: 14, right: 14 },
        tableWidth: 'auto',
        theme: 'grid',
        didDrawPage: (data) => {
            if (data.cursor) {
                y = data.cursor.y;
            }
        },
    });

    // Get current Y position after totals table
    y = (doc as any).lastAutoTable.finalY + 10;

    // Check if we need to add a new page for the remaining content
    const pageHeight = doc.internal.pageSize.getHeight();
    const remainingContentHeight = 80; // Estimated height for the remaining text and signatures

    // If the current Y position plus remaining content exceeds page height, add a new page
    if (y + remainingContentHeight > pageHeight - 20) {
        doc.addPage();
        await addHeaderFooter(2, 2); // Will be updated later with correct total
        y = 50; // Start content at y + 64 on new page
    }
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text('The payment shall be made before 10th.', 15, y);
    y += 7;
    doc.text('Your cooperation on the above is highly appreciated', 15, y);
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Ranhill Technologies Sdn. Bhd.', 15, y);

    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text('Prepared by,', 15, y);
    doc.text('Checked by,', pageWidth / 2 - 28, y);
    doc.text('Approved by,', pageWidth - 73, y);
    y += 15;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('NUR AUFA FIRZANA BINTI SINANG', 15, y);
    doc.text('MUHAMMAD ARIF BIN ABDUL JALIL', pageWidth / 2 - 28, y);
    doc.text('KAMARIAH BINTI YUSOF', pageWidth - 73, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text('Admin Assistant', 15, y);
    doc.text('Senior Executive Administration', pageWidth / 2 - 28, y);
    doc.text('Head of Human Resources and Administration', pageWidth - 73, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text('Date:', 15, y);
    doc.text('Date:', pageWidth / 2 - 28, y);
    doc.text('Date:', pageWidth - 73, y);

    // Add header and footer to all pages with correct page numbers
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        await addHeaderFooter(i, totalPages);
    }

    return new Blob([doc.output('arraybuffer')], { type: 'application/pdf' });
}
